#! /usr/bin/env python
# The line above tells some systems (e.g. Linux/Apple shells) what program to
# use to execute this script.

# Import the libraries we need
import os
import sys
from music21 import (  # noqa: F401
    clef,
    environment,
    metadata,
    meter,
    note,
    stream,
    chord,
    tie,
    volume,
    instrument,
    )

# Tell music21 what to use to play midi and display score

if 'linux' in sys.platform:
    midi_path = '/usr/bin/timidity'
    score_path = '/usr/bin/musescore'
elif sys.platform == 'darwin':
    midi_path = '/usr/local/Cellar/timidity/2.15.0/bin/timidity'
    score_path = '/Applications/MuseScore 3.app/Contents/MacOS/mscore'
    # Need to set the scratch directory or produced midi/musicxml files will
    # not be accessible to the midi/score applications
    environment.set('directoryScratch', os.path.expanduser('~'))
elif sys.platform == 'win32':
    midi_path = os.path.join(
        os.environ["PROGRAMFILES(X86)"], r"Windows Media Player\wmplayer.exe"
    )
    score_path = os.path.join(
        os.environ["PROGRAMW6432"], r"MuseScore 3\bin\MuseScore3.exe"
    )

midi_error = None
score_error = None
if os.path.exists(midi_path):
    environment.set('midiPath', midi_path)
else:
    midi_error = (
        'Could not find midi player. '
        'Looked in {path}'.format(path=midi_path)
    )
if os.path.exists(score_path):
    environment.set('musicxmlPath', score_path)
else:
    score_error = (
        'Could not find MuseScore. Please install MuseScore 3. '
        'Looked in {path}'.format(path=score_path)
    )

# Only run this if the script is executed directly, not imported
if __name__ == '__main__':
    # Complain if there were no arguments passed by the user
    if len(sys.argv) < 3:
        # First, print a helpful message
        print('add a "score" argument to see the score.')
        print('add a "text" argument to see the python objects.')
        print('add a "midi" argument to hear it.')
        print('e.g. To hear the tune: {command} midi'.format(
            command=sys.argv[0],
            ))
        # Now exit without doing anything
        sys.exit()

    tune = None

    src_path = sys.argv[1]
    with open(src_path) as src_handle:
        src = src_handle.read()

    code = compile(
        src,
        os.path.basename(src_path),
        'exec',
    )

    exec(code)

    if not tune:
        sys.stderr.write('Your code does not contain a tune.\n')
        sys.exit(1)

    remaining_args = sys.argv[2:]

    # See if the user put the word 'midi' in the arguments
    if 'midi' in remaining_args:
        # Give hopefully helpful output if we can't play midi
        if midi_error:
            sys.stderr.write(midi_error + '\n')
            sys.stderr.write('NOT PLAYING MIDI\n')
        else:
            # The stream.Score (tune) object knows how to play itself using
            # the environment set midi player and will do so when its show
            # method is called with a 'midi' argument.
            tune.show('midi')

    # See if the user put the word 'text' in the arguments
    if 'text' in remaining_args:
        # The stream.Score (tune) object knows how to display itself as python
        # objects in text, and will do so when its show method is called with
        # a 'text' argument.
        tune.show('text')

    # See if the user put the word 'score' in the arguments
    if 'score' in remaining_args:
        # Give hopefully helpful output if we can't show the score
        if score_error:
            sys.stderr.write(score_error + '\n')
            sys.stderr.write('NOT DISPLAYING MUSICAL SCORE\n')
        else:
            # The stream.Score (tune) object knows how to display itself as
            # musical score, and will do so by default when its show method is
            # called with no arguments.
            tune.show()
